#!/usr/bin/env tclsh
# make-selfx.tcl - build a self-extracting, zlib-compressed single-file build.
#
#   tclsh tools/make-selfx.tcl <input.tcl> <output.tcl>
#
# The output embeds <input.tcl> as a gzip-compressed, base64-encoded payload.
# It launches via the same sh/Tcl polyglot header as the normal build, then
# decompresses and evaluates the payload at startup. This trades readability
# (and the Tcl 8.5 floor) for a much smaller file: ~110 KB instead of ~470 KB.
#
# Requires the *target* interpreter to be Tcl/Tk 8.6+ (zlib, binary decode).

if {[llength $argv] != 2} {
    puts stderr "usage: tclsh make-selfx.tcl <input.tcl> <output.tcl>"
    exit 1
}
lassign $argv in out

set fh [open $in rb]
set data [read $fh]
close $fh

set payload [binary encode base64 [zlib gzip $data -level 9]]

# The polyglot header is the same trick as src/boot.tcl: line 2 ends with a
# backslash so the shell command on line 3 is a Tcl comment continuation (a
# no-op under tclsh), while /bin/sh runs it to re-exec the file under tclsh.
set wfh [open $out w]
chan configure $wfh -encoding utf-8
puts $wfh {#!/bin/sh}
puts $wfh "# sh/Tcl polyglot - backslash continues Tcl comment to next line, hiding shell bootstrap \\"
puts $wfh {_w=$(stty -g 2>/dev/null); trap '[ -n "$_w" ] && stty "$_w" 2>/dev/null' EXIT INT TERM; tclsh "$0" "$@"; exit $?}
puts $wfh ""
puts $wfh "# writhdeck - self-extracting, zlib-compressed build."
puts $wfh "# Generated by tools/make-selfx.tcl - do not edit. Requires Tcl/Tk 8.6+."
puts $wfh {if {[package vcompare [info patchlevel] 8.6] < 0} {puts stderr "writhdeck: this self-extracting build requires Tcl/Tk 8.6+"; exit 1}}
puts $wfh "set _wd_payload \{$payload\}"
puts $wfh {eval [zlib gunzip [binary decode base64 $_wd_payload]]}
close $wfh

catch {file attributes $out -permissions 0755}
puts "Built $out ([file size $out] bytes, from [file size $in] bytes uncompressed)"
